# Site
name: "David Springbok"
title: "David Springbok Travel Blog"
tagline: "El blog que te inspira a recorrer el mundo, a realizar tu sueño de viajar."
description: "Travel blog que muestra rincones del mundo, inspirándote a viajar."
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: ''
google_analytics: 'UA-171108384-1'
disqus: 'demowebsite'
mailchimp-list: 'https://davidspringbok.us10.list-manage.com/subscribe/post?u=258b60f94223c2e6e2ee5b6ad&amp;id=7700ef3958'
include: ["_pages"]
permalink: /:title/
email: imdavid.springbok@gmail.com
url: "https://davidspringbok.com"


# Authors
authors:
  sal:
    name: David Springbok
    display_name: David   
    gravatar: c438fc3d7c456bfcebc7276aaad9ee03
    email: imdavid.springbok@gmail.com
    web: about
    twitter: https://www.facebook.com/davidspringboktravel
    instagram: https://instagram.com/davidspringbok
    description: "Viajero, aventurero y storyller. Ecuatoriano explorando el mundo 🇪🇨."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
# highlighter: none
highlighter: rouge
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "enabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
